import { pgTable, uuid, text, timestamp, doublePrecision, integer, boolean, jsonb, index, } from "drizzle-orm/pg-core";
export const estimations = pgTable("estimations", {
    id: uuid("id").defaultRandom().primaryKey(),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
    lang: text("lang").default("fr").notNull(),
    input: jsonb("input").$type().notNull(),
    itemName: text("item_name").notNull(),
    brand: text("brand"),
    model: text("model"),
    category: text("category"),
    confidence: doublePrecision("confidence").default(0).notNull(),
    aiSource: text("ai_source").default("manual").notNull(),
    hypotheses: jsonb("hypotheses").$type().default([]).notNull(),
    queryText: text("query_text").default("").notNull(),
    condition: text("condition").$type().default("good").notNull(),
    listings: jsonb("listings").$type().default([]).notNull(),
    stats: jsonb("stats").$type().notNull(),
    priceLow: doublePrecision("price_low").default(0).notNull(),
    priceMid: doublePrecision("price_mid").default(0).notNull(),
    priceHigh: doublePrecision("price_high").default(0).notNull(),
    currency: text("currency").default("EUR").notNull(),
    rarity: text("rarity").default("unknown").notNull(),
    demand: text("demand").default("unknown").notNull(),
    sellDaysLow: integer("sell_days_low").default(0).notNull(),
    sellDaysHigh: integer("sell_days_high").default(0).notNull(),
    advice: jsonb("advice").$type().notNull(),
    listingCopy: text("listing_copy").default("").notNull(),
    warnings: jsonb("warnings").$type().default([]).notNull(),
    searchLog: jsonb("search_log").$type().default([]).notNull(),
    soldPrice: doublePrecision("sold_price"),
    soldPlatform: text("sold_platform"),
    soldAt: timestamp("sold_at", { mode: "date" }),
}, (t) => [index("estimations_created_idx").on(t.createdAt)]);
export const priceAlerts = pgTable("price_alerts", {
    id: uuid("id").defaultRandom().primaryKey(),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
    query: text("query").notNull(),
    itemLabel: text("item_label").notNull(),
    currency: text("currency").default("EUR").notNull(),
    baselineMid: doublePrecision("baseline_mid").default(0).notNull(),
    baselineLow: doublePrecision("baseline_low").default(0).notNull(),
    baselineHigh: doublePrecision("baseline_high").default(0).notNull(),
    direction: text("direction").default("any").notNull(), // rise | drop | any
    active: boolean("active").default(true).notNull(),
    lastCheckedAt: timestamp("last_checked_at", { mode: "date" }),
    lastMid: doublePrecision("last_mid"),
    lastChangePct: doublePrecision("last_change_pct"),
}, (t) => [index("alerts_created_idx").on(t.createdAt)]);
